In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import os
import pickle


In [3]:
with open("data.txt", "r", encoding='utf-8') as f:
    text_data = f.read()


In [4]:
text_data

"my name is tanjina proma. I work in IUB.\nHi, I'm Tanjina Proma, a passionate Machine Learning Engineer.\nI am enhancing my knowledge with the latest development in the field of Machine Learning and Data Science.\nI have worked for more than four years, and I have a record of successfully implementing Computer Vision and Image Processing based pipelines with practical expertise using MLOps, deep learning & machine learning. \nI am interested in enabling machine to understand sequence of information and act accordingly to make significant progress towards true artificial intelligence.\n\nI am currently working in IUB as a Lecturer. I am teaching CIS101 and CSE100 courses.\nSince 2024 i am working there. I have also started Masters over there. MSc degree takes 2 years to complete. I am hoping  to finish it before required timeframe.\nI am pursuing MSc in CSC. Along with that i am also doing research work.\n "

In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts([text_data])

In [6]:
tokenizer

In [29]:
sequence = tokenizer.texts_to_sequences([text_data ])[0]

In [30]:
sequence

[13,
 24,
 25,
 14,
 15,
 2,
 16,
 4,
 17,
 26,
 27,
 14,
 15,
 9,
 28,
 6,
 7,
 29,
 2,
 3,
 30,
 13,
 31,
 10,
 18,
 32,
 33,
 4,
 18,
 34,
 11,
 6,
 7,
 5,
 35,
 36,
 2,
 12,
 37,
 38,
 39,
 40,
 41,
 19,
 5,
 2,
 12,
 9,
 42,
 11,
 43,
 44,
 45,
 46,
 5,
 47,
 48,
 49,
 50,
 10,
 51,
 52,
 53,
 54,
 55,
 7,
 6,
 7,
 2,
 3,
 56,
 4,
 57,
 6,
 8,
 58,
 59,
 11,
 60,
 5,
 61,
 62,
 8,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 2,
 3,
 70,
 20,
 4,
 17,
 71,
 9,
 72,
 2,
 3,
 73,
 74,
 5,
 75,
 76,
 77,
 78,
 2,
 3,
 20,
 21,
 2,
 12,
 22,
 79,
 80,
 81,
 21,
 23,
 82,
 83,
 84,
 19,
 8,
 85,
 2,
 3,
 86,
 8,
 87,
 88,
 89,
 90,
 91,
 2,
 3,
 92,
 23,
 4,
 93,
 94,
 10,
 95,
 2,
 3,
 22,
 96,
 97,
 16]

In [32]:
len(sequence)
# len of the unique words in the text data, which is 5000 as we set num_words=5000 in the tokenizer

150

In [33]:
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

In [43]:
max_seq_len = 100
def create_dataset(seq, window_size = max_seq_len):
    input, labels = [], []
    for i in range(len(seq) - window_size):
        input.append(seq[i:i+window_size])
        labels.append(seq[i+1:i+1 +window_size])

    return np.array(input), np.array(labels)

In [44]:
create_dataset(sequence)

(array([[13, 24, 25, ...,  9, 72,  2],
        [24, 25, 14, ..., 72,  2,  3],
        [25, 14, 15, ...,  2,  3, 73],
        ...,
        [ 9, 42, 11, ...,  2,  3, 22],
        [42, 11, 43, ...,  3, 22, 96],
        [11, 43, 44, ..., 22, 96, 97]], shape=(50, 100)),
 array([[24, 25, 14, ..., 72,  2,  3],
        [25, 14, 15, ...,  2,  3, 73],
        [14, 15,  2, ...,  3, 73, 74],
        ...,
        [42, 11, 43, ...,  3, 22, 96],
        [11, 43, 44, ..., 22, 96, 97],
        [43, 44, 45, ..., 96, 97, 16]], shape=(50, 100)))

In [45]:
x_data, y_data = create_dataset(sequence)

In [46]:
x_data[0]

array([13, 24, 25, 14, 15,  2, 16,  4, 17, 26, 27, 14, 15,  9, 28,  6,  7,
       29,  2,  3, 30, 13, 31, 10, 18, 32, 33,  4, 18, 34, 11,  6,  7,  5,
       35, 36,  2, 12, 37, 38, 39, 40, 41, 19,  5,  2, 12,  9, 42, 11, 43,
       44, 45, 46,  5, 47, 48, 49, 50, 10, 51, 52, 53, 54, 55,  7,  6,  7,
        2,  3, 56,  4, 57,  6,  8, 58, 59, 11, 60,  5, 61, 62,  8, 63, 64,
       65, 66, 67, 68, 69,  2,  3, 70, 20,  4, 17, 71,  9, 72,  2])

In [47]:
len(x_data)

50

In [48]:
y_data

array([[24, 25, 14, ..., 72,  2,  3],
       [25, 14, 15, ...,  2,  3, 73],
       [14, 15,  2, ...,  3, 73, 74],
       ...,
       [42, 11, 43, ...,  3, 22, 96],
       [11, 43, 44, ..., 22, 96, 97],
       [43, 44, 45, ..., 96, 97, 16]], shape=(50, 100))

In [49]:
x_data[0]

array([13, 24, 25, 14, 15,  2, 16,  4, 17, 26, 27, 14, 15,  9, 28,  6,  7,
       29,  2,  3, 30, 13, 31, 10, 18, 32, 33,  4, 18, 34, 11,  6,  7,  5,
       35, 36,  2, 12, 37, 38, 39, 40, 41, 19,  5,  2, 12,  9, 42, 11, 43,
       44, 45, 46,  5, 47, 48, 49, 50, 10, 51, 52, 53, 54, 55,  7,  6,  7,
        2,  3, 56,  4, 57,  6,  8, 58, 59, 11, 60,  5, 61, 62,  8, 63, 64,
       65, 66, 67, 68, 69,  2,  3, 70, 20,  4, 17, 71,  9, 72,  2])

In [50]:
y_data[0]

array([24, 25, 14, 15,  2, 16,  4, 17, 26, 27, 14, 15,  9, 28,  6,  7, 29,
        2,  3, 30, 13, 31, 10, 18, 32, 33,  4, 18, 34, 11,  6,  7,  5, 35,
       36,  2, 12, 37, 38, 39, 40, 41, 19,  5,  2, 12,  9, 42, 11, 43, 44,
       45, 46,  5, 47, 48, 49, 50, 10, 51, 52, 53, 54, 55,  7,  6,  7,  2,
        3, 56,  4, 57,  6,  8, 58, 59, 11, 60,  5, 61, 62,  8, 63, 64, 65,
       66, 67, 68, 69,  2,  3, 70, 20,  4, 17, 71,  9, 72,  2,  3])

In [51]:
len(x_data), len(y_data)

(50, 50)

In [52]:
class PositioanEncoding(layers.Layer):
    def __init__(self, max_seq_len, d_model):
        super().__init__()
        pos = np.arange(max_seq_len)[:, np.newaxis]
        i = np.arange(d_model)[np.newaxis, :]
        angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
        angle_rads = pos * angle_rates
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
        self.pos_encoding = tf.cast(angle_rads[np.newaxis, ...] , dtype=tf.float32)

    def call(self, x):
        return x + self.pos_encoding[:, :tf.shape(x)[1], :] 
    

In [1]:
def transformer_block(embed_dim, num_heads, ff_dim, dropout =0.1):
    input = layers.input(shape=(None, embed_dim))
    attn_output = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)(input, input)
    attn_output = layers.Dropout(dropout)(attn_output)
    out1 = layers.LayerNormalization(epsilon=1e-6)(input + attn_output)

    ffn = tf.keras.Sequential([
        layers.Dense(ff_dim, activation='relu'),
        layers.Dense(embed_dim)
    ])

    ffn_output = ffn(out1)
    ffn_output = layers.Dropout(dropout)(ffn_output)
    out2 = layers.LayerNormalization(epsilon=1e-6)(out1 + ffn_output)   
    return tf.keras.Model(inputs=input, outputs=out2)  


In [2]:
vocab_size = 5000
max_seq_len = 100
embed_dim = 128
num_heads = 4
ff_dim = 1024
num_layers = 4
batch_size = 32
epoch = 10

def build_gpt_models():
    input = layers.Input(shape=(max_seq_len,))
    x = layers.Embeddings(vocab_size, embed_dim)(input)
    x = PositioanEncoding(max_seq_len, embed_dim)(x)
 
    for _ in range(num_layers):
        x = transformer_block(embed_dim, num_heads, ff_dim)(x)

    output = layers.Dense(vocab_size, activation='softmax')(x)
    model = tf.keras.Model(inputs=input, outputs=output)
    return model